#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/nix/store/v56q2gjrc389p5vpma7pb4mf5bsagpch-vscode-1.106.2/lib/vscode/code" "/home/martijn/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"