source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/misc.conf

source = ./conf/monitors.conf
source = ./conf/workspaces.conf

exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

# env = XCURSOR_SIZE,24
# env = HYPRCURSOR_SIZE,24
# env = HYPRCURSOR_THEME,Bibata-Modern-Classic  # Replace Bibata-Modern-Ice with the name of the theme you downloaded
# env = HYPRCURSOR_SIZE,24                  # Replace 24 with your desired size

###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow


#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general


# https://wiki.hyprland.org/Configuring/Variables/#animations

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]





# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

device {
    name = --hid-gaming-mouse
    sensitivity = -0.9
}

cursor {
    hide_on_key_press = true
}
