# https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = us,us
    kb_variant = ,dvp
    kb_model =
    kb_options = caps:super,grp:shifts_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        clickfinger_behavior = 1
    }
}
