monitor = DP-8, 1920x1080@75, -1920x0, 1
monitor = DP-7, 1920x1080@144, 0x0, 1
monitor = eDP-1, 1920x1080@165, 1920x0, 1

#monitor = DP-1, 1280x960@144.00Hz, 0x0, 1
#monitor = eDP-1, 1920x1080@165, 1280x0, 1

workspace = 1, monitor:DP-7
workspace = 2, monitor:DP-8
workspace = 3, monitor:DP-7
workspace = 4, monitor:DP-7
workspace = 5, monitor:DP-8
workspace = 6, monitor:DP-8
workspace = 7, monitor:eDP-1
workspace = 8, monitor:DP-7
workspace = 9 monitor:DP-7
