exec-once = hyprpaper & hypridle & swaync
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 5 silent] kitty
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
