#layerrule = blur, rofi
#layerrule = blur, waybar
#layerrule = blur, swaync-control-center

windowrule = match:class ^(gamescope)$, immediate on, fullscreen on, border_size 0, no_blur on, rounding 0, no_anim on
windowrule = match:class cs2, fullscreen on
windowrule = match:class SDL Application, fullscreen on
