windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = tile, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

layerrule = blur, waybar
layerrule = blur, swaync
layerrule = blur, rofi
